### ISSUE TITLE
Exception generating unremarkable profile

### ISSUE THREAD

**Issue by marvingreenberg** [marvingreenberg/FaceSVG#25]
Plugin needs some love.  

no implicit conversion to float from nil
layout.rb:140:in `initialize'
*layout.rb:140:in `new'
*layout.rb:140:in `block in layout_facegrps'
*su_util.rb:296:in `block in capture_faceprofiles'
*su_util.rb:248:in `each'
*su_util.rb:248:in `capture_faceprofiles'
*layout.rb:138:in `layout_facegrps'
*layout.rb:121:in `process_selection'
*main.rb:43:in `block in facesvg_2d_layout'
*su_util.rb:37:in `su_operation'
*main.rb:43:in `facesvg_2d_layout'
*main.rb:112:in `block (2 levels) in <module:FaceSVG>'
*SketchUp:1:in `call'

[f404.skp.zip](https://github.com/marvingreenberg/FaceSVG/files/2825707/f404.skp.zip)

Selecting both faces and clicking 'layout" results in the exception.

**Comment by marvingreenberg** [comment]
Seems  fixed with latest plugin or maybe latest sketchup
